spring:
  application:
    name: vendora

  datasource:
    url: jdbc:mysql://localhost:3306/vendora
    username: root
    password: Root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000